# Generated by Django 4.2.10 on 2025-01-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("height", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("winter", models.CharField(blank=True, default="", max_length=2)),
                ("summer", models.CharField(blank=True, default="", max_length=2)),
                ("autumn", models.CharField(blank=True, default="", max_length=2)),
                ("spring", models.CharField(blank=True, default="", max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("fam", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("otc", models.CharField(blank=True, default="", max_length=150)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Pereval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beauty_title", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("other_titles", models.CharField(max_length=255)),
                ("connect", models.TextField(blank=True, default="")),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "coords",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pereval_api.coords",
                    ),
                ),
                (
                    "level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pereval_api.level",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pereval_api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.ImageField(upload_to="images/")),
                ("title", models.CharField(max_length=255)),
                (
                    "pereval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pereval_api.pereval",
                    ),
                ),
            ],
        ),
    ]
