# Generated by Django 4.2.10 on 2025-01-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pereval_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pereval",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("pending", "На модерации"),
                    ("accepted", "Принято"),
                    ("rejected", "Отклонено"),
                ],
                default="new",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="pereval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attached_images",
                to="pereval_api.pereval",
            ),
        ),
    ]
